version: "3"

services:
  dev:
    build:
      context: .
    ports:
      - 3000:3000
    command: npm run start
    volumes:
      - "./src:/srv/app/src"

  test:
    build:
      context: .
    environment:
      - CI=true
    command: npm run test
